apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-helloworld
  labels:
    app: helm-helloworld
    chart: helm-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-helloworld
  template:
    metadata:
      labels:
        app: helm-helloworld
        
   containers:
        - name: helm-helloworld-container
          image: "asia-northeast3-docker.pkg.dev/erudite-pod-391005/test/test831-app:v1"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
              
          env:
          - name: PRINT_VALUES
            value: {{.Values.printValues}}
          command: ["/bin/sh","-c"]
          args: 
          - while true; do echo $PRINT_VALUES; sleep 5; done;
