apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello_canary
  labels:
    track: canary
    version: {{default .Chart.AppVersion }}
spec:
  replicas: {{ .Values.replicaCount }}
 # strategy:
 #   type: RollingUpdate
 #   rollingUpdate:
 #     maxSurge: 1
 #     maxUnavailable: 0
  selector:
    matchLabels:
      release: hello_canary
  template:
    metadata:
      labels:
        selectorLabels: hello_canary
    spec:
      serviceAccountName: {{ include "hello-world.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}_canary
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
