apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-world.fullnamecanary" . }}
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
    track: canary
    version: {{default .Chart.AppVersion }}
spec:
  replicas: 1
 # strategy:
 #   type: RollingUpdate
 #   rollingUpdate:
 #     maxSurge: 1
 #     maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "hello-world.selectorLabels" . | nindent 6 }}
      release: hello-canary
  replicas: 1
  template:
    metadata:
      labels:
        selectorLabels: hello-canary
    spec:
      serviceAccountName: {{ include "hello-world.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-canary
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
