{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Loadbalancer
metadata:
  name: {{ include "hello-world.fullname" . }}
  app: hello-canary
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    app: hello-canary
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "hello-world.fullname" . }}
                app: hello-canary
                port:
                  name: http
{{- end -}}
